In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [8]:
data=pd.read_csv(r"C:\Users\DINESH\OneDrive\Desktop\Third Year Gayatri\DSBDL\Social_Network_Ads .csv")

In [9]:
data

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [10]:
data_Gender=pd.get_dummies(data['Gender'])
print(data_Gender)

     Female  Male
0         0     1
1         0     1
2         1     0
3         1     0
4         0     1
..      ...   ...
395       1     0
396       0     1
397       1     0
398       0     1
399       1     0

[400 rows x 2 columns]


In [11]:
data.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [12]:
data['Purchased'].unique()

array([0, 1], dtype=int64)

In [13]:
gender=pd.get_dummies(data["Gender"],drop_first=True)
gender

Male
0       1
1       1
2       0
3       0
4       1
..    ...
395     0
396     1
397     0
398     1
399     0

[400 rows x 1 columns]

In [14]:
data["Gender"]=gender
data.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510       1   19            19000          0
1  15810944       1   35            20000          0
2  15668575       0   26            43000          0
3  15603246       0   27            57000          0
4  15804002       1   19            76000          0

In [28]:
data.describe()

User ID      Gender         Age  EstimatedSalary   Purchased
count  4.000000e+02  400.000000  400.000000       400.000000  400.000000
mean   1.569154e+07    0.490000   37.655000     69742.500000    0.357500
std    7.165832e+04    0.500526   10.482877     34096.960282    0.479864
min    1.556669e+07    0.000000   18.000000     15000.000000    0.000000
25%    1.562676e+07    0.000000   29.750000     43000.000000    0.000000
50%    1.569434e+07    0.000000   37.000000     70000.000000    0.000000
75%    1.575036e+07    1.000000   46.000000     88000.000000    1.000000
max    1.581524e+07    1.000000   60.000000    150000.000000    1.000000

In [30]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
data['Age']=scaler.fit_transform(data[['Age']])
data['EstimatedSalary']=scaler.fit_transform(data[['EstimatedSalary']])

In [31]:
data.describe()

User ID      Gender           Age  EstimatedSalary   Purchased
count  4.000000e+02  400.000000  4.000000e+02     4.000000e+02  400.000000
mean   1.569154e+07    0.490000 -2.331468e-16    -1.193490e-17    0.357500
std    7.165832e+04    0.500526  1.001252e+00     1.001252e+00    0.479864
min    1.556669e+07    0.000000 -1.877311e+00    -1.607506e+00    0.000000
25%    1.562676e+07    0.000000 -7.550313e-01    -7.852897e-01    0.000000
50%    1.569434e+07    0.000000 -6.256110e-02     7.561451e-03    0.000000
75%    1.575036e+07    1.000000  7.970571e-01     5.361289e-01    1.000000
max    1.581524e+07    1.000000  2.134241e+00     2.356750e+00    1.000000

In [56]:
x=data[['Gender','Age','EstimatedSalary']]  ## Features
y=data['Purchased'] ## Target

In [33]:
print(x.shape)
print(y.shape)

(400, 3)
(400,)


In [34]:
y.value_counts()

0    257
1    143
Name: Purchased, dtype: int64

# Split the dataset into training and testing datasets.

In [35]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,train_size=0.8)


In [36]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,train_size=0.8,random_state=6)

In [37]:
ytrain.value_counts()

0    205
1    115
Name: Purchased, dtype: int64

# Logistic Regression

In [38]:
from sklearn.linear_model import LogisticRegression
log=LogisticRegression()
log.fit(xtrain,ytrain)

LogisticRegression()

In [39]:
ypred=log.predict(xtest)
ypred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0], dtype=int64)

In [40]:
ytest.values

array([1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0], dtype=int64)

In [41]:
from sklearn.metrics import accuracy_score
score=accuracy_score(ytest,ypred)
score

0.8875

# Change Threshold Value

In [42]:
ypred_new=log.predict_proba(xtest)
ypred_new

array([[0.8214493 , 0.1785507 ],
       [0.96910222, 0.03089778],
       [0.97178707, 0.02821293],
       [0.91486379, 0.08513621],
       [0.99528746, 0.00471254],
       [0.64786881, 0.35213119],
       [0.99187998, 0.00812002],
       [0.66120119, 0.33879881],
       [0.5110051 , 0.4889949 ],
       [0.82094007, 0.17905993],
       [0.85343422, 0.14656578],
       [0.10304116, 0.89695884],
       [0.52967294, 0.47032706],
       [0.91346982, 0.08653018],
       [0.96422753, 0.03577247],
       [0.61476894, 0.38523106],
       [0.66068924, 0.33931076],
       [0.73323156, 0.26676844],
       [0.25081742, 0.74918258],
       [0.64918005, 0.35081995],
       [0.14309393, 0.85690607],
       [0.90184934, 0.09815066],
       [0.9704019 , 0.0295981 ],
       [0.95820049, 0.04179951],
       [0.48084324, 0.51915676],
       [0.68002678, 0.31997322],
       [0.5406962 , 0.4593038 ],
       [0.05198524, 0.94801476],
       [0.11357535, 0.88642465],
       [0.9704019 , 0.0295981 ],
       [0.

In [45]:
threshold=0.4
ypred_new=log.predict_proba(xtest)[:,1]
ypred_new

array([0.1785507 , 0.03089778, 0.02821293, 0.08513621, 0.00471254,
       0.35213119, 0.00812002, 0.33879881, 0.4889949 , 0.17905993,
       0.14656578, 0.89695884, 0.47032706, 0.08653018, 0.03577247,
       0.38523106, 0.33931076, 0.26676844, 0.74918258, 0.35081995,
       0.85690607, 0.09815066, 0.0295981 , 0.04179951, 0.51915676,
       0.31997322, 0.4593038 , 0.94801476, 0.88642465, 0.0295981 ,
       0.02945363, 0.01658262, 0.60951801, 0.00222737, 0.52050396,
       0.76037993, 0.55890311, 0.89421859, 0.00796012, 0.20688325,
       0.33106879, 0.33646421, 0.00898259, 0.0576066 , 0.07712255,
       0.01771968, 0.97618947, 0.34381999, 0.85264695, 0.19373111,
       0.91913695, 0.94406113, 0.19804323, 0.39247664, 0.00545647,
       0.01816175, 0.68775503, 0.40969593, 0.36160603, 0.72483207,
       0.97806706, 0.0497632 , 0.94486879, 0.31471682, 0.44936262,
       0.39119046, 0.00730645, 0.10779365, 0.88136009, 0.04755172,
       0.8615273 , 0.63337465, 0.51636406, 0.31872281, 0.98474

In [44]:
threshold=0.4
ypred_new=log.predict_proba(xtest)[:,1]
ypred_new=ypred_new>threshold
ypred_new

array([False, False, False, False, False, False, False, False,  True,
       False, False,  True,  True, False, False, False, False, False,
        True, False,  True, False, False, False,  True, False,  True,
        True,  True, False, False, False,  True, False,  True,  True,
        True,  True, False, False, False, False, False, False, False,
       False,  True, False,  True, False,  True,  True, False, False,
       False, False,  True,  True, False,  True,  True, False,  True,
       False,  True, False, False, False,  True, False,  True,  True,
        True, False,  True, False,  True, False, False, False])

In [46]:
threshold=0.4
ypred_new=log.predict_proba(xtest)[:,1]
ypred_new=ypred_new>=threshold
ypred_new=ypred_new.astype('int')
ypred_new

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0])

In [47]:
from sklearn.metrics import accuracy_score
score=accuracy_score(ytest,ypred_new)
score

0.825

# KNN

In [48]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=3)
knn.fit(xtrain,ytrain)
ypred_knn=knn.predict(xtest)
ypred_knn

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0], dtype=int64)

In [49]:
from sklearn.metrics import accuracy_score
score=accuracy_score(ytest,ypred_knn)
score

0.9375

In [50]:
from sklearn.metrics import recall_score,precision_score,f1_score

In [54]:
recall = recall_score(ytest,ypred_knn)
precision=precision_score(ytest,ypred_knn)
f1 = f1_score(ytest,ypred_knn)
print("Recall:",recall)
print("Precision:",precision)
print("F1-Score:",f1)

Recall: 0.9285714285714286
Precision: 0.896551724137931
F1-Score: 0.912280701754386


In [55]:
recall = recall_score(ytest,ypred)
precision=precision_score(ytest,ypred)
f1 = f1_score(ytest,ypred)
print("Recall:",recall)
print("Precision:",precision)
print("F1-Score:",f1)

Recall: 0.7857142857142857
Precision: 0.88
F1-Score: 0.830188679245283
